In [2]:
import requests
import pandas as pd
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Your FRED API key
API_KEY = "0f38e32c2e981eed28544328383782cf"

# CPI data series ID (e.g., CPI for All Urban Consumers: All Items in U.S. City Average)
SERIES_ID = "PAYEMS"

# API endpoint
url = f"https://api.stlouisfed.org/fred/series/observations"

# Parameters for the API request
params = {
    "series_id": SERIES_ID,
    "api_key": API_KEY,
    "file_type": "json",
    "frequency": "m",  # Monthly data
    "observation_start": "2020-01-01",  # Adjust start date as needed
}

# Fetch data from FRED API
response = requests.get(url, params=params, verify=False)

if response.status_code == 200:
    data = response.json()
    # Parse observations into a DataFrame
    observations = data["observations"]
    df = pd.DataFrame(observations)
    df["date"] = pd.to_datetime(df["date"])
    df["value"] = pd.to_numeric(df["value"])
    print(df.head())
else:
    print(f"Failed to fetch data. Status code: {response.status_code}")
    print(response.text)

  realtime_start realtime_end       date   value
0     2025-01-10   2025-01-10 2020-01-01  152045
1     2025-01-10   2025-01-10 2020-02-01  152309
2     2025-01-10   2025-01-10 2020-03-01  150898
3     2025-01-10   2025-01-10 2020-04-01  130421
4     2025-01-10   2025-01-10 2020-05-01  133040

In [3]:
df

   realtime_start realtime_end       date   value
0      2025-01-10   2025-01-10 2020-01-01  152045
1      2025-01-10   2025-01-10 2020-02-01  152309
2      2025-01-10   2025-01-10 2020-03-01  150898
3      2025-01-10   2025-01-10 2020-04-01  130421
4      2025-01-10   2025-01-10 2020-05-01  133040
5      2025-01-10   2025-01-10 2020-06-01  137655
6      2025-01-10   2025-01-10 2020-07-01  139240
7      2025-01-10   2025-01-10 2020-08-01  140774
8      2025-01-10   2025-01-10 2020-09-01  141820
9      2025-01-10   2025-01-10 2020-10-01  142493
10     2025-01-10   2025-01-10 2020-11-01  142761
11     2025-01-10   2025-01-10 2020-12-01  142518
12     2025-01-10   2025-01-10 2021-01-01  142916
13     2025-01-10   2025-01-10 2021-02-01  143443
14     2025-01-10   2025-01-10 2021-03-01  144274
15     2025-01-10   2025-01-10 2021-04-01  144593
16     2025-01-10   2025-01-10 2021-05-01  145044
17     2025-01-10   2025-01-10 2021-06-01  145822
18     2025-01-10   2025-01-10 2021-07-01  146761
19     2025-01-10   2025-01-10 2021-08-01  147226
20     2025-01-10   2025-01-10 2021-09-01  147706
21     2025-01-10   2025-01-10 2021-10-01  148566
22     2025-01-10   2025-01-10 2021-11-01  149197
23     2025-01-10   2025-01-10 2021-12-01  149763
24     2025-01-10   2025-01-10 2022-01-01  150014
25     2025-01-10   2025-01-10 2022-02-01  150876
26     2025-01-10   2025-01-10 2022-03-01  151370
27     2025-01-10   2025-01-10 2022-04-01  151642
28     2025-01-10   2025-01-10 2022-05-01  151928
29     2025-01-10   2025-01-10 2022-06-01  152348
30     2025-01-10   2025-01-10 2022-07-01  153038
31     2025-01-10   2025-01-10 2022-08-01  153281
32     2025-01-10   2025-01-10 2022-09-01  153536
33     2025-01-10   2025-01-10 2022-10-01  153897
34     2025-01-10   2025-01-10 2022-11-01  154155
35     2025-01-10   2025-01-10 2022-12-01  154291
36     2025-01-10   2025-01-10 2023-01-01  154773
37     2025-01-10   2025-01-10 2023-02-01  155060
38     2025-01-10   2025-01-10 2023-03-01  155206
39     2025-01-10   2025-01-10 2023-04-01  155484
40     2025-01-10   2025-01-10 2023-05-01  155787
41     2025-01-10   2025-01-10 2023-06-01  156027
42     2025-01-10   2025-01-10 2023-07-01  156211
43     2025-01-10   2025-01-10 2023-08-01  156421
44     2025-01-10   2025-01-10 2023-09-01  156667
45     2025-01-10   2025-01-10 2023-10-01  156832
46     2025-01-10   2025-01-10 2023-11-01  157014
47     2025-01-10   2025-01-10 2023-12-01  157304
48     2025-01-10   2025-01-10 2024-01-01  157560
49     2025-01-10   2025-01-10 2024-02-01  157796
50     2025-01-10   2025-01-10 2024-03-01  158106
51     2025-01-10   2025-01-10 2024-04-01  158214
52     2025-01-10   2025-01-10 2024-05-01  158430
53     2025-01-10   2025-01-10 2024-06-01  158548
54     2025-01-10   2025-01-10 2024-07-01  158692
55     2025-01-10   2025-01-10 2024-08-01  158770
56     2025-01-10   2025-01-10 2024-09-01  159025
57     2025-01-10   2025-01-10 2024-10-01  159061
58     2025-01-10   2025-01-10 2024-11-01  159288

In [4]:
159288-159061

227